### ISSUE TITLE
Adding guidelines for prospective contributors

### ISSUE THREAD

**Issue by cbrueffer** [codemeleon/seqPanther#10]
Some guidelines for prospective contributors would be useful, as highlighted also in the JOSS review checklist. A good example is Biopython, where information is mentioned both in the project README, and in more detail in https://github.com/biopython/biopython/blob/master/CONTRIBUTING.rst

This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/5305

**Comment by jsan4christ** [comment]
Thanks @cbrueffer.

This has been addressed in commit [5ccc42c](https://github.com/codemeleon/seqPanther/commit/5ccc42c09d3e9087867caeb7351bdcc11d43d7ae).
