### ISSUE TITLE
Manuscript: reference issue

### ISSUE THREAD

**Issue by cbrueffer** [codemeleon/seqPanther#11]
There seems to be an issue with one citation in the manuscript, `molecular clock 19 and`, not sure which reference is intended here.

https://github.com/codemeleon/seqPanther/blob/master/manuscript/paper.md?plain=1#LL88C1394-L88C1394

This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/5305

**Comment by jsan4christ** [comment]
Thanks for picking this up.

It is:

Natural selection on synonymous mutations in SARS-CoV-2 and the impact on estimating divergence time (https://doi.org/10.2217/fvl-2021-0078)

---
Estimation of the genuine divergence time based on synonymous sites
We have shown that the synonymous mutations in SARS-CoV-2 do not occur under constant rate, and that they also undergo natural selection. Both features hinder the accurate estimation of divergence time based on synonymous sites.
---

I have corrected accordingly.
