### ISSUE TITLE
what version(s) of Python does seqPanther work with?

### ISSUE THREAD

**Issue by ctb** [codemeleon/seqPanther#5]
I'm testing it out with python 3.10. Curious what the lowest version is? It's not described in the readme or setup.py as far as I can tell.

(over in sourmash we try to follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html))

**Comment by jsan4christ** [comment]
Thanks for highlighting that. The README is updated to show the supported Python versions. The application should run without a problem on Python 3.7 or greater. You should be fine with 3.10.
